# Intuition

Think of Linear Regression as a simple line equation like we did in middle school. You have your equation y = mx + b which plots a relationship between to variables (x and y). The x variable can be viewed as your predictor or "independent variable". The other variable, y is your dependent variable. What this means is y's growth is depenent on the growth of x! 

This is the same exact concept used for linear regression! The model uses statistical methods to return the expected model of y as a linear funciton of x:  
y = β0 + β1*x + ε  

Here β0 and β1 are the parameters your computer is trying to find out to best fit the relationship of the two variables. β0 is the y inctercept and β1 is the slope of the system. In our model, we are predicting values and our model won't be 100% accurate. For this reason, we need to create an error term, ε, which represents the difference between our actual and predicted values. 

It is very rare for our system have a linear correlation between data points where this simple explanation can work, but it good for us to start connecting mathematics to these simple concepts

# Mathematics

## Linear Algebra

For our linear regression, we have a system of linear equations that can be represented in a matrix in the form of y = β0 + β1*x + ε as stated previously.
y = β0 + β1*x + ε 
- y is a nx1 vector of our target values that we will be predicting
- X is a nxm matrix of input features we will be plugging in to predict our output
- β0 is the y intercept of the regression line. It represents the predicted value of y when our input vector is 0
- β1 is the mx1 matrix of parameters we want to estimate for our model.
- ε is a n x 1 vector of the error terms

Our goal is to find the β0 and β1 that minimizes the sum of the squared residuals. Remember residuals are the difference between the observed, actual values and predicted values of the target variable.  We can achieve this by setting the derivative of the sum of our squared resuiduals with respect to the parameter β1 equal to zero.
From this, we are given the solution β1 = (X^t * X)^-1 * (X^t * Y). We have to transpose our vectors due to their dimensions.  ^t and -1 are the transpose and inverse respectively. The stars are just regular matrix multiplication and aren't implying any specfics in particular.

### Solving for intercept
In the matrix notation of linear regression, y = Xβ + ε, the intercept is included in the β vector. To include the intercept, a column of ones is added to the matrix X. This means that the first element of β (β0) is multiplied by one, so it acts as a constant term in the equation.

The parameters β (including β0) are usually estimated by minimizing the sum of squared residuals. This can be done using the normal equation:

β = (X'X)^-1 X'y

where X' is the transpose of X and (X'X)^-1 is the inverse of X'X. The first element of the resulting β vector will be β0.

In the context of your code, once you have solved for β using the QR decomposition and back substitution, the first element of the resulting β vector will be your intercept, β0.

### Solving for Slope
At this point, we have to calculate the inverse of the matrix which can be computationally expensive and numerically unstable. This is important since the operation of matrix inversion is sensitive to the values in the matrix. If X^t*X is close to being singular(not invertible), small changes can lead to large changes in the inverse which can lead to smlarge changes in the estimated parameters. For this reason, matrix decomposition is super important! We can use it to factor the methods into the product of two or more matrices which makes it way easier to compute the inverse. Methods such QR decomposition can be used to factor our matrix X into the product of an Orthogonal matrix Q and Upper trinagle Matrix R. Once we have this we can solve for β1*x.  

X'Xβ = X'Y  
QR'QRβ = QR'Y  
R'QRβ = R'Q'Y  
Rβ = Q'Y  

Since R is an upper triangle matrix, we can easily solve this system of equations efficiently using back substitution.
Remember there are many other methods such as Cholesky Decomp which can be used!

## Vector Calculus and Optimization
[Read/Watch for this portion: Gradient Descent](https://builtin.com/data-science/gradient-descent)  
As stated previously, our goal is to find the values of β0 (intercept) and β1 (slope) that minimize the sum of the squared residuals (ε). This is equivalent to minimizing the cost function J(β), defined as:

J(β) = 1/2n * Σ(y_i - (β0 + β1*x_i))^2

where:
- n is the number of observations,
- y_i is the observed value of the target variable for observation i,
- x_i is the value of the predictor variable for observation i.

To find the minimum of J(β), we use vector calculus. Specifically, we calculate the gradient of J(β), which is a vector that contains the partial derivatives of J(β) with respect to each parameter. For simple linear regression, the gradient is a 2-dimensional vector:

∇J(β) = [ ∂J/∂β0, ∂J/∂β1 ]

The partial derivatives are calculated as follows:

∂J/∂β0 = 1/n * Σ(y_i - (β0 + β1*x_i))

∂J/∂β1 = 1/n * Σ((y_i - (β0 + β1*x_i)) * x_i)

Setting these equal to zero gives us the normal equations, which can be solved to find the parameters that minimize the cost function:

Σ(y_i - (β0 + β1*x_i)) = 0

Σ((y_i - (β0 + β1*x_i)) * x_i) = 0

Solving these equations gives us the values of β0 and β1 that minimize the cost function J(β). This process is known as gradient descent.

In each iteration of gradient descent, we update the parameters by subtracting a fraction of the gradient from the current parameter values. The size of this step is determined by the learning rate, a hyperparameter that controls how fast the algorithm converges to the optimal parameters. Utilizing a learning rate is good! However, sometimes we might run into oscillations jumping back and forth across the valley of the cost function without moving towards the minimum. Momentum allows us to mitigate this issue by adding a fraction of the past iteration to the current update vector which kind of acts like a damper for a spring. This would help reduce the oscillations and allow us to converge on the minimum point faster! By doing so, we could potentially reach the local minimum sooner.

This iterative process continues until the algorithm converges to a set of parameters that minimize the cost function, i.e., the error between the predicted and actual values is minimized. At this point, the gradient of the cost function is zero (or close to zero), indicating that any small change in the parameters will not significantly decrease the cost function.

## Analytical Geometry
Remember our goal in a 2D space (one independent and one target variable) is to find the straight line that best fits these points. This line called the regression line is 1D in shape essentially only projecting a straight line through our plane. The best line mimizes the sum of our squared residuals(mimimizes our cost)! However, it is very rare we will have only one independent variable. For this, we can think of a multi-dimensional spaces where each dimension represents an independent variable. The regression line is now a hyperplane that spans across multiple dimensions!

This is where analytical geometry comes in. How are we going to fit our hyperplane in the multi-dimensional space. We can find the shortest distance from each data point to the hyper plane. That distance is the residual! This sum becomes part of the Optimization problem talked about above. There are many methods we use to calculate this but two in particular which are used heavily are L1 and L2 Norm.

### **L1 Norm (Manhattan Distance)**: 
The L1 norm calculates the sum of the absolute differences between two points (or vectors). In a 2D space, it's equivalent to the distance you would travel if you could only move along a grid of horizontal and vertical lines (like in a city block), hence the name Manhattan distance. The formula for L1 norm for two points A(x1, y1) and B(x2, y2) is:


L1 = abs(x1 - x2) + abs(y1 - y2)  

Pros:  
    1. **Sparsity**: L1 norm tends to produce sparse solutions, meaning it tends to produce solutions where many of the coefficients are zero. This can be useful for feature selection, as it can help identify the most important features.
    2. **Robustness to Outliers**: L1 norm is more robust to outliers than L2 norm. This is because it does not square the residuals, so large residuals (outliers) do not have as much influence on the solution.

Cons:  
    1. **Multiple Solutions**: L1 norm can have multiple solutions, especially when the number of features is greater than the number of observations. This can make the solution less stable and harder to interpret.
    2. **Computationally Intensive**: Finding the solution can be more computationally intensive than for L2 norm, especially for large datasets.



### **L2 Norm (Euclidean Distance)**: 
The L2 norm calculates the square root of the sum of the squares of the differences between two points (or vectors). In a 2D space, it's equivalent to the straight-line distance between two points, hence the name Euclidean distance. The formula for L2 norm for two points A(x1, y1) and B(x2, y2) is:


L2 = sqrt((x1 - x2)^2 + (y1 - y2)^2)  

Pros:  
    1. **Unique Solution**: L2 norm always has a unique solution, which can make it more stable and easier to interpret than L1 norm.
    2. **Efficient Computation**: The solution can be found analytically (i.e., using a formula), which can be more computationally efficient than for L1 norm.

Cons:  
    1. **Not Robust to Outliers**: L2 norm squares the residuals, so large residuals (outliers) have a large influence on the solution. This can make the solution less robust to outliers than L1 norm.
    2. **No Feature Selection**: L2 norm does not produce sparse solutions, so it does not perform feature selection like L1 norm. This can make the solution harder to interpret when there are many features.

# Code in Scikit-learn

In [16]:
import numpy as np  
import matplotlib.pyplot as plt
import pandas as pd 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts 
import seaborn as sns
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

### Importing Data

In [12]:
dataset = pd.read_csv('Datasets/50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [15]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [14]:
print(X.shape) # n * m array
print(y.shape) # n * 1 array
# we now know state is a categorical variable

(50, 4)
(50,)


### Encoding Features

In [17]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough') # allows us to target the column we want to encode
X = np.array(ct.fit_transform(X))

Dummy Variables:
- Dummy variables are binary variables representing categories. For a category like "color" with values "red", "blue", "green", you'd create dummy variables "color_red", "color_blue", "color_green".
- The Dummy Variable Trap is a scenario where dummy variables cause perfect multicollinearity, meaning they are highly correlated. This happens if all dummy variables for a category are included in a regression model.
- To avoid the Dummy Variable Trap, one dummy variable for each category should be left out of the model. This left-out category becomes the "reference category".
- The coefficients on the included dummy variables represent changes relative to the reference category.
- Some libraries for regression automatically avoid the Dummy Variable Trap by excluding one category for each set of dummy variables.

In [18]:
print(X) #New york, california, florida

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

### Creating Train Test split

In [19]:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.2, random_state = 0)

### Training Model

In [21]:
regressor = LinearRegression(fit_intercept=True, copy_X=True, n_jobs=None, positive=False) # default hyperparamters for tuning model!
regressor.fit(X_train, y_train)

LinearRegression()

### Prediction

In [22]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2) #2 decimal places
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #compare predicted and actual values
# reshape allows us to create a n x 1 array for easier comparison, last 1 is axis which means itll concatenate along the columns

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


## Evaluation

In [23]:
r_squared = regressor.score(X_test, y_test)
print(f'R-squared: {r_squared}')

R-squared: 0.9347068473282341


## NOTES FOR READER
this is a super simple dataset! I didn't modify my hyperparameters at all. I just wanted to connect the relationship between the math and the code.